Add new utility functions: m/explain-data, m/data-explainer, mu/keys
metosin/malli pull request #707
Opened 2022-05-23 13:33 UTC by opqdonut

The main issue I'm trying to fix here is not being able to serialize the output of m/explain. See commit message for more.

mu/keys was just something simple I've been missing so I'm adding it in the same PR :)

2022-05-23 13:33 UTC, opqdonut commented on src/malli/util.cljc
> +  [?schema]
I'm not sure what the `?schema` convention was for, but I've followed it here.

2022-05-23 13:34 UTC, opqdonut commented on src/malli/core.cljc
> +  (:require [clojure.walk :as walk]
I'm not sure why clojure.walk was only required in clj mode. Perhaps to reduce cljs bundle size? If so, I can move the data-explainer to malli.util, or alternatively rewrite it without using clojure.walk.

2022-05-23 14:56 UTC, ikitommi requested changes
Good and clean PR, some changes requested.

2022-05-24 05:47 UTC, opqdonut commented on src/malli/core.cljc
> +        (walk/prewalk schema->data (explainer' value in acc)))))))
Good point. I was under the impression that the errors can somehow nest and you can have a `:schema` at any level, but what you say makes sense. Done.

2022-05-24 05:48 UTC, opqdonut commented on test/malli/core_test.cljc
> +(#:clj
added one

2022-05-24 05:48 UTC, opqdonut commented on src/malli/core.cljc
> +  (:require [clojure.walk :as walk]
good point, moved to malli.util

2022-05-24 05:51 UTC, opqdonut commented on test/malli/util_test.cljc
> +(deftest keys-test
Done!

2022-05-24 05:52 UTC, opqdonut commented
I didn't rebase/squash anything to make reviewing easier. I can squash this into two nice commits if you want.

2022-05-24 07:08 UTC, ikitommi approved these changes
looks really good, please update the docs (at least CHANGELOG) before/after merging.

2022-05-24 07:08 UTC, ikitommi commented on src/malli/util.cljc
> +         schema->data (fn [s]
side-note: it's always a `Schema`, so `schema->data` could be replaced just with `m/form`.

2022-05-25 14:23 UTC, merged