Add clj-kondo support for cljs function schemas
metosin/malli pull request #833
Opened 2023-02-01 01:49 UTC by dvingo

Fixes https://github.com/metosin/malli/issues/828

After lots of help from Thomas Heller [here](https://app.slack.com/client/T03RZGPFR/C6N245JGG/thread/C6N245JGG-1674780762.779839) I was able to put together a much simpler dev experience for cljs.

This PR adds kondo config and updates the docs with Thomas' recommended setup using a preload and namespace ordering by the compiler to ensure your function schemas are up to date when `malli.dev.cljs/start!` is evaluated at compile-time.

I updated the kondo `save!` function to emit to a different location for clj and cljs schemas so you can seamlessly use both during development. Let me know if you have any concerns or feedback about that .

2023-02-01 07:00 UTC, thheller requested changes
Small tweaks, then it should be fine.

2023-02-01 16:21 UTC, dvingo commented
Thanks @thheller ! updated per your feedback : )

2023-02-01 16:54 UTC, thheller approved these changes
Looks good. Although in plugin part you can just call the above function instead of repeating the code.

2023-02-01 18:07 UTC, dvingo commented
> n part you can just call the above function instead of repeating the code.

ah of course - updated

2023-02-02 19:33 UTC, merged

2023-02-02 19:35 UTC, ikitommi commented
This is really well though though, implemented and documented 🙇